### ISSUE TITLE
Problem Displaying Model Explanation and Prediction Explanation

### ISSUE THREAD

**Issue by sdfungayi** [biolab/orange3-explain#26]
I am running a churn prediction workflow as shown in the attached image.
My class of interest is YES

1. The "Explain Model" widget displays only a vertical strip when I set the class to YES but displays model explanation graphic properly when I set the class to NO
2. Similarly, the "Explain Prediction" widget displays only a vertical line when I set the class to YES but displays prediction explanation graphic properly when I  set the class to NO

What am I doing wrong?

How do I get make the graphics display properly when the class is set to YES?

![Workflow](https://user-images.githubusercontent.com/81328264/118060546-47bc0180-b393-11eb-930f-f35f1b21704b.JPG)
![Explain Prediction - No](https://user-images.githubusercontent.com/81328264/118060549-48ed2e80-b393-11eb-9298-996ff71dd00f.JPG)
![Explain Prediction - Yes](https://user-images.githubusercontent.com/81328264/118060552-4985c500-b393-11eb-976d-6bd2273b225d.JPG)
![Explain Model - No](https://user-images.githubusercontent.com/81328264/118060553-4a1e5b80-b393-11eb-98ee-d3b466d5a215.JPG)
![Explain Model - Yes](https://user-images.githubusercontent.com/81328264/118060554-4ab6f200-b393-11eb-8d61-1ee3e50dc600.JPG)

**Comment by sdfungayi** [comment]
Thank you @PrimozGodec

**Comment by VesnaT** [comment]
This was a problem in the SHAP library and should have been fixed with the newest version.

**Comment by ajdapretnar** [comment]
Thanks for looking into it. But I still have an issue with shap==0.40.0.
Use heart_disease.tab with Gradient Boosting.

![Screen Shot 2021-12-17 at 12 04 42](https://user-images.githubusercontent.com/12524972/146535373-41996406-1474-4dd7-a741-bc82d1878e94.png)

**Comment by VesnaT** [comment]
I see. I only checked it for the Iris dataset.

**Comment by PrimozGodec** [comment]
Closing via https://github.com/biolab/orange3-explain/pull/50
